title: "Semantic differences (DiscriminAtt) task from SemEval 2018"
description: "A benchmark task on recognizing discriminative attributes, attributes that distinguish one word from another."
spacy_version: ">=3.1.0,<4.0.0"

vars:
  config: "train"  # or "dev" or occasionally "test"
  model: "intermediate/semdiff_thinc.bin"

directories: ["assets", "intermediate", "metrics"]

assets:
  -
    dest: "assets/DiscriminAtt"
    git:
        repo: "https://github.com/dpaperno/DiscriminAtt/"
        branch: "master"
        path: ""

workflows:
  all:
    - train
    - evaluate

commands:
  - name: clean
    help: "Remove intermediate files"
    script:
      - "rm -rf intermediate/*"
      - "rm -rf metrics/*"

  - train:
      help: "Train the semantic differences classifier"
      script:
        - "python scripts/train_semdiff.py ${vars.model}"
      deps:
        - "assets/DiscriminAtt"
        - "scripts/semdiff_matt.py"
      outputs:
        - "${vars.model}"
  - name: evaluate
    help: "Run the SemEval-2018 DiscriminAtt evaluation"
    script:
      - "python scripts/evaluate_semdiff.py ${vars.model} metrics/accuracy.json"
    deps:
      - "scripts/evaluate_semdiff.py"
      - "${vars.model}"
    outputs:
      - "metrics/accuracy.json"
